---
- hosts: all
  become: true
  name: example2
  tasks:
    - name: update Debian
      ansible.builtin.apt:
        update_cache: false
      when: ansible_os_family == 'Debian'

    - name: update RedHat
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

- hosts: web-server2
  become: true
  tasks:
    - name: Check nginx installed
      ansible.builtin.stat:
        path: /usr/share/nginx
      register: nginx_installed

    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      when: nginx_installed.stat is not defined

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started